project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://rashika-auti.github.io/STA9750-2025-FALL/"
  navbar:
    background: primary
    search: false
    left:
      - text: "Home"
        href: index.qmd
    right:
      - text: "MP#01"
        href: mp01.html
      - text: "MP#02"
        href: mp02.html
      - text: "MP#03"
        href: mp03.html
      - text: "MP#04"
        href: mp04.html    
    
format:
  html:
    theme: # trying to place a toggle button for light and dark theme choice, but still figuring it out
      light: sandstone
      dark: darkly
    toggle: true
    toc: false
    css: styles.css

editor:
  mode: source